Repository FromDoppler/doppler-users-api, pull requests merged in 2021-08, with the labels that each got.

#14 feat: return state code in province attribute
  Doppler.UsersApi/Infrastructure/AccountRepository.cs
Labels: size/XS

#12 feat: add new features
  Doppler.UsersApi.Test/GetFeaturesTest.cs
  Doppler.UsersApi/Infrastructure/FeaturesRepository.cs
  Doppler.UsersApi/Model/Features.cs
Labels: size/S

#15 feat: return state code on update
  Doppler.UsersApi/Infrastructure/AccountRepository.cs
Labels: size/XS

#16 feat: [DAT-526] Add decrypt/encrypt service
  Dockerfile
  Doppler.UsersApi.Test/EncryptionTest/EncryptionEnvironmentTests.cs
  Doppler.UsersApi.Test/EncryptionTest/EncryptionServiceTests.cs
  Doppler.UsersApi.Test/EncryptionTest/EncryptionServiceWithRealConfigurationTests.cs
  Doppler.UsersApi.Test/EncryptionTest/EncryptionTestHelpers.cs
  Doppler.UsersApi.Test/GetContactInformationTest.cs
  Doppler.UsersApi/Encryption/EncryptionService.cs
  Doppler.UsersApi/Encryption/EncryptionSettings.cs
  Doppler.UsersApi/Encryption/IEncryptionService.cs
  Doppler.UsersApi/Infrastructure/AccountRepository.cs
  Doppler.UsersApi/Model/ContactInformation.cs
  Doppler.UsersApi/Startup.cs
  Doppler.UsersApi/appsettings.Development.json
  Jenkinsfile
  build-n-publish.sh
Labels: size/L

#18 feat: [DAT-537] add validations for contact information
  Doppler.UsersApi.Test/ContactInformationValidatorTest.cs
  Doppler.UsersApi.Test/GetContactInformationTest.cs
  Doppler.UsersApi.Test/UpdateContactInformationTest.cs
  Doppler.UsersApi/Controllers/AccountController.cs
  Doppler.UsersApi/Doppler.UsersApi.csproj
  Doppler.UsersApi/Encryption/EncryptionService.cs
  Doppler.UsersApi/Encryption/IEncryptionService.cs
  Doppler.UsersApi/Infrastructure/AccountRepository.cs
  Doppler.UsersApi/Startup.cs
  Doppler.UsersApi/Validators/ContactInformationValidator.cs
Labels: size/L

#19 fix: fix features query
  Doppler.UsersApi/Infrastructure/FeaturesRepository.cs
Labels: size/XS

#20 chore: [No ticket ] Remove answer question validate and encryption
  Doppler.UsersApi.Test/ContactInformationValidatorTest.cs
  Doppler.UsersApi/Infrastructure/AccountRepository.cs
  Doppler.UsersApi/Validators/ContactInformationValidator.cs
Labels: size/M

#21 fix: [No-Ticket] Remove unnecessary validation
  Doppler.UsersApi.Test/ContactInformationValidatorTest.cs
  Doppler.UsersApi/Validators/ContactInformationValidator.cs
Labels: size/S
