Repository FromDoppler/doppler-users-api, pull requests merged in 2021-07, with the labels that each got.

#3 test: move test controller to test project
  Doppler.UsersApi.Test/AuthorizationTest.cs
  Doppler.UsersApi.Test/Controllers/HelloController.cs
  Doppler.UsersApi.Test/Utils/HttpResponseMessageExtensions.cs
Labels: size/L

#4 chore: remove the example weather controller
  Doppler.UsersApi.Test/IntegrationTest.cs
  Doppler.UsersApi/Controllers/WeatherForecastController.cs
  Doppler.UsersApi/Startup.cs
  Doppler.UsersApi/WeatherForecast.cs
Labels: size/M

#2 feat: give functionality to features endpoint
  Doppler.UsersApi.Test/Doppler.UsersApi.Test.csproj
  Doppler.UsersApi.Test/GetFeaturesTest.cs
  Doppler.UsersApi.Test/IntegrationTest.cs
  Doppler.UsersApi.Test/Utils/ServiceCollectionExtensions.cs
  Doppler.UsersApi/Controllers/FeatureController.cs
  Doppler.UsersApi/Doppler.UsersApi.csproj
  Doppler.UsersApi/Infrastructure/DatabaseConnectionFactory.cs
  Doppler.UsersApi/Infrastructure/DopplerDatabaseSettings.cs
  Doppler.UsersApi/Infrastructure/FeaturesRepository.cs
  Doppler.UsersApi/Infrastructure/IDatabaseConnectionFactory.cs
  Doppler.UsersApi/Infrastructure/IDopplerDatabaseSettings.cs
  Doppler.UsersApi/Infrastructure/IFeaturesRepository.cs
  Doppler.UsersApi/Infrastructure/InfrastructureServiceCollectionExtensions.cs
  Doppler.UsersApi/Logging/SerilogSetup.cs
  Doppler.UsersApi/Model/Features.cs
  Doppler.UsersApi/Startup.cs
  Doppler.UsersApi/appsettings.Development.json
  Doppler.UsersApi/appsettings.json
Labels: size/L

#7 fix: improve get features parameters
  Doppler.UsersApi.Test/Controllers/HelloController.cs
  Doppler.UsersApi/Controllers/FeatureController.cs
  Doppler.UsersApi/DopplerSecurity/IsOwnResourceAuthorizationHandler.cs
Labels: size/XS

#5 Dat 466 add account controller with contact information endpoint
  Doppler.UsersApi.Test/GetContactInformationTest.cs
  Doppler.UsersApi/Controllers/AccountController.cs
  Doppler.UsersApi/Infrastructure/AccountRepository.cs
  Doppler.UsersApi/Infrastructure/IAccountRepository.cs
  Doppler.UsersApi/Infrastructure/InfrastructureServiceCollectionExtensions.cs
  Doppler.UsersApi/Model/ContactInformation.cs
Labels: size/L

#11 [DAT-504] - Return Industry code
  Doppler.UsersApi/Infrastructure/AccountRepository.cs
Labels: size/S

#13 [DAT-489] - Add update contact information endpoint
  Doppler.UsersApi.Test/UpdateContactInformationTest.cs
  Doppler.UsersApi/Controllers/AccountController.cs
  Doppler.UsersApi/Infrastructure/AccountRepository.cs
  Doppler.UsersApi/Infrastructure/IAccountRepository.cs
  Doppler.UsersApi/Model/ContactInformation.cs
Labels: size/L
